In [1]:
#pandas is a libray it contains functions related to the database
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
#Now we are going to convert categorial data column (Sex and Smoker) as Numerical numbers using One Hot Encoding 
dataset=pd.get_dummies(dataset,drop_first=True) # Nominal data to adrenal data get, while giving drop_first=True function it'll drop extra column.,drop_first=True
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns #It'll show all dataset columns. we can use it for further process related.

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
#Input and output split
#Data was already preprocessed. Now we are going to perform Input and output variables split
indep=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']] 
indep #Now 'age', 'bmi', 'children', 'sex_female', 'sex_male','smoker_no', 'smoker_yes' column values seperately assigned into independent varaiable, Independent means input, Dependent means output.

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
#Now 'charges' column value seperately assigned into dependent varaiable, dependent means output.
dep=dataset[["charges"]] #Now charges value seperately assigned into dependent varaiable,
dep
#Now we got seperatley independent and dependent varaiables. now sucessfully splited input and output

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
#Model Creation
#ML algorithm all are provided by sklearn, we are creting this Model using trainset and tesset varaiable. 
from sklearn.model_selection import GridSearchCV #sklearn.model_selection import GridSearchCV, here GridSearchCV means create table and validate all the parameter values in multiple angle/combination. CV means cross validation.
#Using GridSerachCV(CV-cross validation) means create table in box and check all combination of parameters values and providing results in multiple angle like above.
#GridSerachCV--cross validation going to happen and it's related Gridsearch also going to perform here
from sklearn.ensemble import RandomForestRegressor # While calling, this line loaded into memory. here SVR may be function or class. In this line SVR considered as class
param_grid={'criterion':['mse','mae'],
           'max_features': ['auto','sqrt','log2'],
            'n_estimators':[10,100]}
#playable paramerters using to check correct combination and provide result in tabular format.param_grid varaiable created and {} curley brace( {} dictionary) we can call it as dictionary. kernal means key('kernal':'rbf','poly','sigmoid','linear') and C means(10,100,1000,2000,3000).
#We have defined all the playable parameter values. Now going to call this model.
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True, verbose=3,n_jobs=1) #Here we calling GridSearchCV() and here we are passing SVR and passing parameters.refit=True means which one is best model take it as last model(). GridSearchCV() final output use it for best model. 'refit=False' means it will take last combination as (c:300, gmma:scale) like that only it'll take. 
#First four lines call it as procedure load. inside grid varaiable all models are there
#fitting the model for grid search
grid.fit(indep,dep) #fit function we are calling it using access operator, now passing splited trainset input and output.
#while executing above step fit() method model has been created. we got total model 120 model combination created.n_jobs=-1 means parallely running all models. once executed this it'll show all the executed parameter details.
#All models saved under grid varaiable.

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

Fitting 3 folds for each of 12 candidates, totalling 36 fits
[CV] criterion=mse, max_features=auto, n_estimators=10 ...............
[CV]  criterion=mse, max_features=auto, n_estimators=10, score=0.830, total=   0.0s
[CV] criterion=mse, max_features=auto, n_estimators=10 ...............
[CV]  criterion=mse, max_features=auto, n_estimators=10, score=0.808, total=   0.0s
[CV] criterion=mse, max_features=auto, n_estimators=10 ...............
[CV]  criterion=mse, max_features=auto, n_estimators=10, score=0.815, total=   0.0s
[CV] criterion=mse, max_features=auto, n_estimators=100 ..............
[CV]  criterion=mse, max_features=auto, n_estimators=100, score=0.839, total=   0.3s
[CV] criterion=mse, max_features=auto, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mse, max_features=auto, n_estimators=100, score=0.825, total=   0.2s
[CV] criterion=mse, max_features=auto, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mse, max_features=auto, n_estimators=100, score=0.819, total=   0.2s
[CV] criterion=mse, max_features=sqrt, n_estimators=10 ...............
[CV]  criterion=mse, max_features=sqrt, n_estimators=10, score=0.836, total=   0.0s
[CV] criterion=mse, max_features=sqrt, n_estimators=10 ...............
[CV]  criterion=mse, max_features=sqrt, n_estimators=10, score=0.804, total=   0.0s
[CV] criterion=mse, max_features=sqrt, n_estimators=10 ...............
[CV]  criterion=mse, max_features=sqrt, n_estimators=10, score=0.790, total=   0.0s
[CV] criterion=mse, max_features=sqrt, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mse, max_features=sqrt, n_estimators=100, score=0.842, total=   0.2s
[CV] criterion=mse, max_features=sqrt, n_estimators=100 ..............
[CV]  criterion=mse, max_features=sqrt, n_estimators=100, score=0.833, total=   0.2s

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV] criterion=mse, max_features=sqrt, n_estimators=100 ..............
[CV]  criterion=mse, max_features=sqrt, n_estimators=100, score=0.815, total=   0.2s
[CV] criterion=mse, max_features=log2, n_estimators=10 ...............
[CV]  criterion=mse, max_features=log2, n_estimators=10, score=0.837, total=   0.0s
[CV] criterion=mse, max_features=log2, n_estimators=10 ...............
[CV]  criterion=mse, max_features=log2, n_estimators=10, score=0.820, total=   0.0s
[CV] criterion=mse, max_features=log2, n_estimators=10 ...............
[CV]  criterion=mse, max_features=log2, n_estimators=10, score=0.795, total=   0.0s
[CV] criterion=mse, max_features=log2, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mse, max_features=log2, n_estimators=100, score=0.844, total=   0.2s
[CV] criterion=mse, max_features=log2, n_estimators=100 ..............
[CV]  criterion=mse, max_features=log2, n_estimators=100, score=0.834, total=   0.2s
[CV] criterion=mse, max_features=log2, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mse, max_features=log2, n_estimators=100, score=0.817, total=   0.2s
[CV] criterion=mae, max_features=auto, n_estimators=10 ...............
[CV]  criterion=mae, max_features=auto, n_estimators=10, score=0.827, total=   0.2s
[CV] criterion=mae, max_features=auto, n_estimators=10 ...............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=auto, n_estimators=10, score=0.816, total=   0.2s
[CV] criterion=mae, max_features=auto, n_estimators=10 ...............
[CV]  criterion=mae, max_features=auto, n_estimators=10, score=0.798, total=   0.2s
[CV] criterion=mae, max_features=auto, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=auto, n_estimators=100, score=0.826, total=   1.6s
[CV] criterion=mae, max_features=auto, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=auto, n_estimators=100, score=0.830, total=   1.6s
[CV] criterion=mae, max_features=auto, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=auto, n_estimators=100, score=0.817, total=   1.6s
[CV] criterion=mae, max_features=sqrt, n_estimators=10 ...............
[CV]  criterion=mae, max_features=sqrt, n_estimators=10, score=0.831, total=   0.1s
[CV] criterion=mae, max_features=sqrt, n_estimators=10 ...............
[CV]  criterion=mae, max_features=sqrt, n_estimators=10, score=0.827, total=   0.1s

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV] criterion=mae, max_features=sqrt, n_estimators=10 ...............
[CV]  criterion=mae, max_features=sqrt, n_estimators=10, score=0.792, total=   0.1s
[CV] criterion=mae, max_features=sqrt, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=sqrt, n_estimators=100, score=0.841, total=   1.0s
[CV] criterion=mae, max_features=sqrt, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=sqrt, n_estimators=100, score=0.833, total=   1.0s
[CV] criterion=mae, max_features=sqrt, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=sqrt, n_estimators=100, score=0.818, total=   1.0s
[CV] criterion=mae, max_features=log2, n_estimators=10 ...............
[CV]  criterion=mae, max_features=log2, n_estimators=10, score=0.833, total=   0.1s
[CV] criterion=mae, max_features=log2, n_estimators=10 ...............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=log2, n_estimators=10, score=0.813, total=   0.1s
[CV] criterion=mae, max_features=log2, n_estimators=10 ...............
[CV]  criterion=mae, max_features=log2, n_estimators=10, score=0.822, total=   0.1s
[CV] criterion=mae, max_features=log2, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=log2, n_estimators=100, score=0.841, total=   1.0s
[CV] criterion=mae, max_features=log2, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=log2, n_estimators=100, score=0.831, total=   1.0s
[CV] criterion=mae, max_features=log2, n_estimators=100 ..............

C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:516: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

[CV]  criterion=mae, max_features=log2, n_estimators=100, score=0.823, total=   1.0s

[Parallel(n_jobs=1)]: Done  36 out of  36 | elapsed:   13.9s finished
C:\Users\Kathirvel\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:715: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators='warn', n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=1,
             param_grid={'criterion': ['mse', 'mae'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [8]:
#print the best parameter after tunning
#print(grid.best_params_)
re=grid.cv_results_  #grid.cv_results() value stored in re varaiable. #here grid.cv_results() in this table stroed in dictionary format. readability will be poor,if it'sin table format means it will be good.
print("The R_Score value for best parameter {}:".format(grid.best_params_)) #Gridsearch  again used training dataset to display best parameter.

The R_Score value for best parameter {'criterion': 'mae', 'max_features': 'log2', 'n_estimators': 100}:

In [9]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.025668,9.427969e-04,0.004000,1.123916e-07,mse,auto,10,"{'criterion': 'mse', 'max_features': 'auto', '...",0.830109,0.808407,0.814965,0.817827,0.009088,8
1,0.230680,4.497170e-03,0.016001,8.164374e-04,mse,auto,100,"{'criterion': 'mse', 'max_features': 'auto', '...",0.838983,0.825426,0.819258,0.827889,0.008239,5
2,0.020001,1.123916e-07,0.003333,4.714266e-04,mse,sqrt,10,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.835593,0.803946,0.789950,0.809830,0.019092,12
3,0.172343,9.031524e-03,0.014334,4.715390e-04,mse,sqrt,100,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.841876,0.833069,0.814896,0.829947,0.011233,4
4,0.021001,1.414111e-03,0.005000,8.168267e-04,mse,log2,10,"{'criterion': 'mse', 'max_features': 'log2', '...",0.836616,0.819762,0.794850,0.817076,0.017157,9
5,0.168343,8.178948e-03,0.014334,4.713704e-04,mse,log2,100,"{'criterion': 'mse', 'max_features': 'log2', '...",0.844213,0.834304,0.816589,0.831702,0.011427,2
6,0.156676,3.399474e-03,0.004000,2.247832e-07,mae,auto,10,"{'criterion': 'mae', 'max_features': 'auto', '...",0.826527,0.815712,0.797819,0.813353,0.011838,11
7,1.590091,2.647153e-02,0.014001,1.123916e-07,mae,auto,100,"{'criterion': 'mae', 'max_features': 'auto', '...",0.825909,0.830470,0.817182,0.824520,0.005513,6
8,0.105339,6.847897e-03,0.004000,1.123916e-07,mae,sqrt,10,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.831263,0.827430,0.792411,0.817035,0.017482,10
9,0.975056,7.789296e-03,0.013668,4.713142e-04,mae,sqrt,100,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.840563,0.832947,0.818341,0.830617,0.009220,3
10,0.099006,2.160274e-03,0.004667,4.714266e-04,mae,log2,10,"{'criterion': 'mae', 'max_features': 'log2', '...",0.833025,0.812577,0.822030,0.822544,0.008355,7
11,0.964722,6.182813e-03,0.014001,1.123916e-07,mae,log2,100,"{'criterion': 'mae', 'max_features': 'log2', '...",0.841388,0.831398,0.822864,0.831883,0.007570,1

In [10]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
Children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:56
BMI:67
Children:78
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [11]:
Future_Prediction=grid.predict([[age_input,bmi_input,Children_input,sex_male_input,smoker_yes_input]]) #change the parameter
#here (grid.predict) we have given  grid and refit=True was given so that best Models model was saved under this grid. while predicting we got the same. 
print("Future_Prediction={}".format(Future_Prediction))
#using grid.predict you can predict best model.if it's good model save it and go for deployment phase.
#incase if you want use Decision tree algorithm means just change below two lines(param_grid and SVR) and perform operations.
#from sklearn.svm import SVR # While calling, this line loaded into memory. here SVR may be function or class. In this line SVR considered as class
#param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
#           'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
#SLR,MLR we don't have playable parameters, so use these paramaters in Decision tree,RF,SVM and use GridSerachCV create table and predict best result.

Future_Prediction=[45737.2361014]